name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Update Version in Cargo.toml
        run: |
          version=${GITHUB_REF#refs/tags/}
          sed -i "s/^version = \".*\"/version = \"$version\"/" Cargo.toml

      - name: Build
        run: cargo build --release

      - name: Generate Feature List
        run: |
          echo "::set-output name=feature_list::$(cargo run --release --bin random-things -- generate-feature-list)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: ${{ github.event_name == 'pull_request' }}
          body: |
            # ${{ github.ref }}

            ${{ steps.generate_feature_list.outputs.feature_list }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/random-things.exe
          asset_name: random-things.exe
          asset_content_type: application/octet-stream